### PR TITLE
Added Turkish suppressions

### PR DESCRIPTION
**Pull request by ozdemirburak**
Greetings, 

I've just added Turkish suppressions, but as you can see, I have not compiled anything for the dist folder.

Here is the source: [TDK](https://en.wikipedia.org/wiki/Turkish_Language_Association), https://tdk.gov.tr/wp-content/uploads/2019/01/K%C4%B1saltmalar_Dizini.pdf

Thanks.

### CODE REVIEW

**Comment by camertron** [comment]
Hey @ozdemirburak thanks for the PR :) I have a couple of questions:

1. It doesn't look like you've added all the suppressions present in the PDF you linked - is that on purpose?
1. Have you considered contributing these suppressions to CLDR? I'm not sure there's an easy way to do so, but it can't hurt to poke around [cldr.unicode.org](http://cldr.unicode.org/).

**Comment by ozdemirburak** [comment]
1. Yes. I've only extracted the ones with a dot. And I also checked them all manually.
2. No, but I'll check it. I think [this is the repository and the directory that hosts suppressions](https://github.com/unicode-org/cldr/tree/master/common/segments), but I think it needs more than a simple Github PR.

**Comment by camertron** [comment]
Makes sense, thanks @ozdemirburak :)

**Comment by camertron** [comment]
Published as v2.2.0.

**Pull request merged**
